"""Initial migration: create all tables

Revision ID: 968df7c9cd79
Revises: 
Create Date: 2025-07-24 18:27:31.316144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968df7c9cd79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('dim_label', sa.String(length=100), nullable=False),
    sa.Column('price_lkr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('iso_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_code')
    )
    op.create_table('message_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_key', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('pw_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tracking_id', sa.String(length=50), nullable=False),
    sa.Column('sender_name', sa.String(length=100), nullable=False),
    sa.Column('sender_phone', sa.String(length=20), nullable=False),
    sa.Column('receiver_name', sa.String(length=100), nullable=False),
    sa.Column('receiver_phone', sa.String(length=20), nullable=False),
    sa.Column('origin_wh_id', sa.UUID(), nullable=False),
    sa.Column('dest_wh_id', sa.UUID(), nullable=False),
    sa.Column('box_type_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('REGISTERED', 'IN_TRANSIT', 'DELIVERED', 'DELAYED', 'CANCELLED', name='packagestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['box_type_id'], ['box_types.id'], ),
    sa.ForeignKeyConstraint(['dest_wh_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['origin_wh_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_tracking_id'), 'packages', ['tracking_id'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('declared_value_lkr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_index(op.f('ix_packages_tracking_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_table('warehouses')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('message_templates')
    op.drop_table('countries')
    op.drop_table('box_types')
    
    op.execute("DROP TYPE IF EXISTS userrole CASCADE")
    op.execute("DROP TYPE IF EXISTS packagestatus CASCADE")
    # ### end Alembic commands ###
